[package]
name = "tokio-cadence"
version = "0.1.0"
authors = ["Peter Nehrer <pnehrer@eclipticalsoftware.com>"]
edition = "2018"

[dependencies]
cadence = "0.22"
log = "0.4"
thiserror = "1.0"
tokio = { version = "0.3", features = ["net"] }

[dev-dependencies.tokio]
features = ["net", "macros", "rt-multi-thread"]
