[package]
name = "tokio-cadence"
version = "0.1.0"
authors = ["Peter Nehrer <pnehrer@eclipticalsoftware.com>"]
edition = "2018"

[dependencies]
cadence = "0.22"
log = "0.4"
tokio = { version = "0.2", features = ["net", "sync", "time"] }

[dev-dependencies]
pretty_env_logger = "0.4"

[dev-dependencies.tokio]
version = "0.2"
features = ["net", "sync", "time", "macros", "rt-threaded"]
